# zetup.py
#
# Zimmermann's Python package setup.
#
# Copyright (C) 2014 Stefan Zimmermann <zimmermann.code@gmail.com>
#
# zetup.py is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# zetup.py is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with zetup.py. If not, see <http://www.gnu.org/licenses/>.

import os
from textwrap import dedent

from path import path as Path

from jinja2 import Environment, FileSystemLoader, TemplateNotFound

from zetup import Zetup
from zetup.commands import ZetupCommandError


class Loader(FileSystemLoader):
    def __init__(self):
        self.templates_dir = Path(__path__[0]) / 'templates'
        super(Loader, self).__init__(self.templates_dir)

    def get_source(self, env, target):
        source, _, uptodate = super(Loader, self).get_source(
          env, target + '.jinja')
        return source, target, uptodate


@Zetup.command
def make(self, *targets):
    if not targets:
        raise ZetupCommandError("No targets given. You can 'make all'.")
    env = Environment(loader=Loader())
    if 'all' in targets:
        targets = [tname.rsplit('.', 1)[0]
                   for tname in os.listdir(env.loader.templates_dir)
                   if tname.endswith('.jinja')]
    for target in targets:
        path = Path(self.ZETUP_DIR) / target
        if path.exists():
            raise ZetupCommandError(
              "Target '%s' already exists. Overwrite with -f or --force"
              % target)
        try:
            template = env.get_template(target)
        except TemplateNotFound:
            raise ZetupCommandError(
              "No template for target '%s'." % target)
        text = template.render({
          'zetup_header': dedent("""
            # This file was auto-generated by zetup
            #
            # https://bitbucket.org/userzimmermann/zetup.py
            """),
          'zfg': self,
          })
        path.write_text(text.strip())
