# zetup.py
#
# Zimmermann's Python package setup.
#
# Copyright (C) 2014 Stefan Zimmermann <zimmermann.code@gmail.com>
#
# zetup.py is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# zetup.py is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with zetup.py. If not, see <http://www.gnu.org/licenses/>.

from textwrap import dedent

from path import path as Path

from jinja2 import Environment, FileSystemLoader

from zetup import Zetup
from zetup.commands import ZetupCommandError


class Loader(FileSystemLoader):
    def __init__(self):
        templates_dir = Path(__path__[0]) / 'templates'
        super(Loader, self).__init__(templates_dir)

    def get_source(self, env, target):
        source, _, uptodate = super(Loader, self).get_source(
          env, target + '.jinja')
        return source, target, uptodate


@Zetup.command
def make(self, *targets):
    if not targets:
        raise ZetupCommandError(
          "No targets given. Make all with -a or --all")
    env = Environment(loader=Loader())
    for target in targets:
        path = Path(self.ZETUP_DIR) / target
        if path.exists():
            raise ZetupCommandError(
              "Target '%s' already exists. Overwrite with -f or --force"
              % target)
        template = env.get_template(target)
        text = template.render()
        path.write_text(dedent("""
          # This file was auto-generated by zetup
          #
          # https://bitbucket.org/userzimmermann/zetup.py

          """) + text.strip())
