#!python

import sys
from textwrap import dedent
from argparse import ArgumentParser
from subprocess import call
import distutils.command

from path import path as Path

import zetup
from zetup import COMMANDS


EXTERNAL_COMMANDS = []

COMMANDS += distutils.command.__all__
COMMANDS += zetup.Zetup.COMMANDS
COMMANDS += EXTERNAL_COMMANDS

ap = ArgumentParser()
ap.add_argument(
  'cmd', choices=COMMANDS,
  help="command",
  )

args = ap.parse_args()

# Generate setup.py if not existing
# (and delete after running commands in that case):
setup_py = Path('setup.py')
create_setup_py = not setup_py.exists()
if create_setup_py:
    setup_py.write_text(dedent("""
      from zetup import Zetup

      zetup = Zetup()
      zetup()
      """))

exit_status = 0 # exit status of this script
try:
    cmdfunc = getattr(zetup, args.cmd)
except AttributeError:
    if args.cmd in EXTERNAL_COMMANDS:
        exit_status = call([args.cmd])
    else:
        zetup = zetup.Zetup()
        if args.cmd in zetup.COMMANDS:
            getattr(zetup, args.cmd)()
        else: # ==> standard setup command
            zetup()
else:
    exit_status = cmdfunc()

# Delete setup.py if generated before:
if create_setup_py:
    setup_py.remove()

sys.exit(exit_status or 0)
