#!python

import sys
from textwrap import dedent
from argparse import ArgumentParser
from subprocess import call
import distutils.command

from path import path as Path

import zetup
from zetup import COMMANDS


EXTERNAL_COMMANDS = ['tox']

COMMANDS += EXTERNAL_COMMANDS
COMMANDS += distutils.command.__all__

ap = ArgumentParser()
ap.add_argument(
  'cmd', choices=COMMANDS,
  help="command",
  )

args = ap.parse_args()

exit_status = 0
try:
    cmdfunc = getattr(zetup, args.cmd)
except AttributeError:
    setup_py = Path('setup.py')
    create_setup_py = not setup_py.exists()
    if create_setup_py:
        setup_py.write_text(dedent("""
          from zetup import Zetup

          zetup = Zetup()
          zetup()
          """))
    if args.cmd in EXTERNAL_COMMANDS:
        exit_status = call([args.cmd])
    else:
        zetup = zetup.Zetup()
        zetup()
    if create_setup_py:
        setup_py.remove()
else:
    cmdfunc()

sys.exit(exit_status)
